variable "db_indentifier" {}
variable "default_tags" {}
variable "db_engine" {}
variable "db_engine_version" {}
variable "db_instance_class" {}
variable "allocated_storage" {}
variable "max_allocated_storage" {}
variable "db_name" {}
variable "db_username_login" {}
variable "db_port" {}
variable "iam_database_authentication_enabled" {}
variable "multi_az" {}
variable "backup_retention_period" {}
variable "db_parameter_family_group" {}
variable "major_engine_version" {}
variable "deletion_protection" {}
variable "cross_region_replica" {}
variable "publicly_accessible" {}
variable "apply_immediately" {}
variable "storage_encrypted" {}
variable "storage_type" {}
variable "db_subnet_group_id" {}
variable "db_subnet_ids" {}
variable "vpc_id" {}
variable "vpc_cidr" {}
variable "delete_automated_backups" {}
variable "option_group_timeouts" {}
variable "create_db_option_group" {}
variable "enable_ssm_storage_sensitive_data" {}
